define october = [
    None,
    ("Tuesday", "First"),
    ("Wednesday", "Second"),
    ("Thursday", "Third"),
    ("Friday", "Fourth"),
    ("Saturday", "Fifth"),
    ("Sunday", "Sixth"),
    ("Monday", "Seventh"),
    ("Tuesday", "Eighth"),
    ("Wednesday", "Ninth"),
    ("Thursday", "Tenth"),
    ("Friday", "Eleventh"),
    ("Saturday", "Twelfth"),
    ("Sunday", "Thirteenth"),
    ("Monday", "Fourteenth"),
    ("Wednesday", "Fifteenth"),
    ("Thursday", "Sixteenth"),
    ("Friday", "Seventeenth"),
    ("Saturday", "Eighteenth"),
    ("Sunday", "Nineteenth"),
    ("Monday", "Twentieth"),
    ("Wednesday", "Twenty-first"),
    ("Thursday", "Twenty-second"),
    ("Friday", "Twenty-third"),
    ("Saturday", "Twenty-fourth"),
    ("Sunday", "Twenty-fifth"),
    ("Monday", "Twenty-sixth"),
    ("Wednesday", "Twenty-seventh"),
    ("Thursday", "Twenty-eighth"),
    ("Friday", "Twenty-ninth"),
    ("Saturday", "Thirtieth"),
    ("Sunday", "Thirty-first"),
]

default calendar_day = 0
