define october = [
    "Monday the Thirtieth",
    "Tuesday the First",
    "Wednesday the Second",
    "Thursday the Third",
    "Friday the Fourth",
    "Saturday the Fifth",
    "Sunday the Sixth",
    "Monday the Seventh",
    "Tuesday the Eighth",
    "Wednesday the Ninth",
    "Thursday the Tenth",
    "Friday the Eleventh",
    "Saturday the Twelfth",
    "Sunday the Thirteenth",
    "Monday the Fourteenth",
    "Wednesday the Fifteenth",
    "Thursday the Sixteenth",
    "Friday the Seventeenth",
    "Saturday the Eighteenth",
    "Sunday the Nineteenth",
    "Monday the Twentieth",
    "Wednesday the Twenty-first",
    "Thursday the Twenty-second",
    "Friday the Twenty-third",
    "Saturday the Twenty-fourth",
    "Sunday the Twenty-fifth",
    "Monday the Twenty-sixth",
    "Wednesday the Twenty-seventh",
    "Thursday the Twenty-eighth",
    "Friday the Twenty-ninth",
    "Saturday the Thirtieth",
    "Sunday the Thirty-first",
]

default calendar_day = 0
